wandb_version: 1

Gamma:
  desc: null
  value: 0.94
Tau:
  desc: null
  value: 1
_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_episode_storage:
  desc: null
  value: None
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: "[[[[0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   ...\n\
    \   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]]\n\n  [[0 0\
    \ 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   ...\n   [0 0 0\
    \ ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]]\n\n  [[0 0 0 ... 0 0\
    \ 0]\n   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   ...\n   [0 0 0 ... 0 0 0]\n\
    \   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]]]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x000002211115B1C8>
_n_calls:
  desc: null
  value: 0
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 500000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1646678195
    t:
      1:
      - 1
      - 2
      - 3
      2:
      - 1
      - 2
      - 3
      3:
      - 2
      - 3
      - 22
      - 34
      4: 3.7.11
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Discrete(4)
actor:
  desc: null
  value: None
algo:
  desc: null
  value: DQN
batch_size:
  desc: null
  value: 32
buffer_size:
  desc: null
  value: 10000
device:
  desc: null
  value: cuda
env:
  desc: null
  value: <stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object
    at 0x000002211116D348>
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
exploration_final_eps:
  desc: null
  value: 0.05
exploration_fraction:
  desc: null
  value: 0.8
exploration_initial_eps:
  desc: null
  value: 1
exploration_rate:
  desc: null
  value: 0.0
exploration_schedule:
  desc: null
  value: <function get_linear_fn.<locals>.func at 0x00000221111A9DC8>
gamma:
  desc: null
  value: 0.94
gradient_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.001
learning_starts:
  desc: null
  value: 50000
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x000002211118A8B8>
max_grad_norm:
  desc: null
  value: 10
n_envs:
  desc: null
  value: 1
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: "Box([[[0 0 0 ... 0 0 0]\n  [0 0 0 ... 0 0 0]\n  [0 0 0 ... 0 0 0]\n  ...\n\
    \  [0 0 0 ... 0 0 0]\n  [0 0 0 ... 0 0 0]\n  [0 0 0 ... 0 0 0]]\n\n [[0 0 0 ...\
    \ 0 0 0]\n  [0 0 0 ... 0 0 0]\n  [0 0 0 ... 0 0 0]\n  ...\n  [0 0 0 ... 0 0 0]\n\
    \  [0 0 0 ... 0 0 0]\n  [0 0 0 ... 0 0 0]]\n\n [[0 0 0 ... 0 0 0]\n  [0 0 0 ...\
    \ 0 0 0]\n  [0 0 0 ... 0 0 0]\n  ...\n  [0 0 0 ... 0 0 0]\n  [0 0 0 ... 0 0 0]\n\
    \  [0 0 0 ... 0 0 0]]], [[[255 255 255 ... 255 255 255]\n  [255 255 255 ... 255\
    \ 255 255]\n  [255 255 255 ... 255 255 255]\n  ...\n  [255 255 255 ... 255 255\
    \ 255]\n  [255 255 255 ... 255 255 255]\n  [255 255 255 ... 255 255 255]]\n\n\
    \ [[255 255 255 ... 255 255 255]\n  [255 255 255 ... 255 255 255]\n  [255 255\
    \ 255 ... 255 255 255]\n  ...\n  [255 255 255 ... 255 255 255]\n  [255 255 255\
    \ ... 255 255 255]\n  [255 255 255 ... 255 255 255]]\n\n [[255 255 255 ... 255\
    \ 255 255]\n  [255 255 255 ... 255 255 255]\n  [255 255 255 ... 255 255 255]\n\
    \  ...\n  [255 255 255 ... 255 255 255]\n  [255 255 255 ... 255 255 255]\n  [255\
    \ 255 255 ... 255 255 255]]], (3, 256, 256), uint8)"
optimize_memory_usage:
  desc: null
  value: 'False'
policy:
  desc: null
  value: "DQNPolicy(\n  (q_net): QNetwork(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (q_net): Sequential(\n\
    \      (0): Linear(in_features=196608, out_features=64, bias=True)\n      (1):\
    \ ReLU()\n      (2): Linear(in_features=64, out_features=64, bias=True)\n    \
    \  (3): ReLU()\n      (4): Linear(in_features=64, out_features=4, bias=True)\n\
    \    )\n  )\n  (q_net_target): QNetwork(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (q_net): Sequential(\n\
    \      (0): Linear(in_features=196608, out_features=64, bias=True)\n      (1):\
    \ ReLU()\n      (2): Linear(in_features=64, out_features=64, bias=True)\n    \
    \  (3): ReLU()\n      (4): Linear(in_features=64, out_features=4, bias=True)\n\
    \    )\n  )\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.dqn.policies.DQNPolicy'>
policy_kwargs:
  desc: null
  value: '{}'
q_net:
  desc: null
  value: "QNetwork(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (q_net): Sequential(\n    (0): Linear(in_features=196608,\
    \ out_features=64, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=64,\
    \ out_features=4, bias=True)\n  )\n)"
q_net_target:
  desc: null
  value: "QNetwork(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (q_net): Sequential(\n    (0): Linear(in_features=196608,\
    \ out_features=64, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=64,\
    \ out_features=4, bias=True)\n  )\n)"
remove_time_limit_termination:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x0000022111194048>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1646678252.4507027
target_update_interval:
  desc: null
  value: 50000
tau:
  desc: null
  value: 1
tensorboard_log:
  desc: null
  value: ./tensorboard_logs/
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1000, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde:
  desc: null
  value: 'False'
use_sde_at_warmup:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
